# Generated by Django 4.2 on 2023-05-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_club_footballer_delete_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballer',
            name='position',
            field=models.IntegerField(blank=True, choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')]),
        ),
    ]
