# Generated by Django 4.2 on 2023-05-05 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fantasy", "0004_alter_footballer_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footballer",
            name="market_value",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="footballer",
            name="position",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Goalkeeper"),
                    (1, "Defender"),
                    (2, "Midfielder"),
                    (3, "Forward"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user_squad",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user_squad",
            name="user_team",
            field=models.TextField(),
        ),
    ]
